batch_size = 32
epochs = 150
lr = 0.01
momentum = 0.9
no_cuda =False
#cuda_id = '0'
seed = 1
log_interval = 10
l2_decay = 5e-4
class_num = 65
param = 0.3
bottle_neck = True
# root_path = "./dataset/"
# source_name = "Product"
# target_name = "Real World"
pseudo_label_th = 0.2
window_size = 0.04
